### ISSUE TITLE
datiTrasmissione.FormatoTrasmissione = "SDI12"

### ISSUE THREAD

**Issue by ilMes** [EtabetaWeb/FatturaElettronica#1]
Le specifiche dicono "FPR12"=privati "FPA12"=verso PA
sarebbe da correggere in
datiTrasmissione.FormatoTrasmissione = "FPR12" '  "FPR12"=privati "FPA12"=verso PA

**Comment by EtabetaWeb** [comment]
Il codice che hai evidenziato fa riferimento al progetto GeneraFatturaPA.v12 che è basato sulla versione 1.2 delle specifiche tecniche dell'Agenzia delle Entrate e prevedeva la sola trasmissione verso le PA.
