### ISSUE TITLE
Mancanza namespace iniziali

### ISSUE THREAD

**Issue by ws-gianni** [EtabetaWeb/FatturaElettronica#2]
Salve,
mi sembra che ci siano delle incongruenze nella sezione dei namespace iniziali.
Dalla documentazione sembra che debba contenere le seguenti informazioni:

<?xml version="1.0" encoding="utf-8"?>
< 
**p:**FatturaElettronica **xsi:schemaLocation="http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.2 fatturaordinaria_v1.2.xsd"**
 xmlns:p="http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ds="http://www.w3.org/2000/09/xmldsig#" 

riassumendo: manca il tag iniziale '**p**' ed il namespace iniziali lo schemalocation per xsi.

Grazie del supporto

**Comment by EtabetaWeb** [comment]
Ciao Gianni,
il codice del progetto GeneraFatturaEL.v13 è stato aggiornato per gestire il tag 'p'.

Un saluto.
Andrea (EtabetaWeb) Cervi
[etabetaweb.com](https://etabetaweb.com)

**Comment by ws-gianni** [comment]
Ciao Andrea,
ho riportato le modifiche e, ovviamente, funziona perfettamente.

Ti ringrazio immensamente per quanto stai facendo per la community.
Gianni
