### ISSUE TITLE
Stesso problema nel namespace radice senza "p:".

### ISSUE THREAD

**Issue by andreamontisci** [EtabetaWeb/FatturaElettronica#3]
Grazie per il materiale e la documentazione incluso il libro che ho acquistato per kindle, anche io ho lo stesso problema sul namespace radice ma essendo alle prome armi con vb.net e xml non sono riuscito ancora a capire come correggerlo. Ciao Andrea.

**Comment by EtabetaWeb** [comment]
Ciao,
il codice GeneraXML è un codice di esempio per l’utilizzo della classe e non è esaustivo né tantomeno vuole essere un programma per generare la fattura. Il cuore del mio lavoro è la classe che espone tutti i nodi e la possibilità di richiamarli come metodi per passare i parametri.

Una possibile soluzione al problema può essere quella di serializzare la classe e rimuovere il nodo iniziale e crearlo a runtime prima di salvare il file. Sto realizzando un altro codice di esempio proprio per risolvere questo problema, ti informo non appena on-line.

Un saluto.

**Comment by EtabetaWeb** [comment]
Ciao Andrea,
il codice del progetto GeneraFatturaEL.v13 è stato aggiornato per gestire il tag 'p'.

Un saluto.
Andrea (EtabetaWeb) Cervi
[etabetaweb.com](https://etabetaweb.com)
